# Generated by Django 3.0.7 on 2020-07-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=models.CharField(max_length=5000),
        ),
    ]
