# Generated by Django 3.0.7 on 2020-07-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0003_auto_20200724_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=models.TextField(max_length=5000),
        ),
    ]
